name: step_tracking
description: A step tracking application using Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pedometer: ^4.0.2             # For step tracking
  fl_chart: ^0.63.0             # For graphs and visualizations
  hive: ^2.2.3                   # Local storage
  hive_flutter: ^1.1.0           # Hive integration for Flutter
  provider: ^6.1.1
  # State management (optional, for managing UI state)
  firebase_core: ^2.22.0            # Initialize Firebase
  cloud_firestore: ^4.12.1          # Firestore for step data
  flutter_native_splash: ^2.3.1     # Splash screen
  rive: ^0.11.0                     # Animation for walking icon
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1          # Generates Hive adapters
  build_runner: ^2.4.6            # Code generation for Hive


flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_image.png

  # If you want to add assets like icons or images, uncomment and modify the lines below:
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # To include fonts, modify the fonts section as needed:
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
